=== L3P3titPrince/015_FetchRewards_HW/data/receipts_std_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Generated schema for Root",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "object",
          "properties": {
            "$oid": {
              "type": "string"
            }
          },
          "required": [
            "$oid"
          ]
        },
        "bonusPointsEarned": {
          "type": "number"
        },
        "bonusPointsEarnedReason": {
          "type": "string"
        },
        "createDate": {
          "type": "object",
          "properties": {
            "$date": {
              "type": "string"
            }
          },
          "required": [
            "$date"
          ]
        },
        "dateScanned": {
          "type": "object",
          "properties": {
            "$date": {
              "type": "string"
            }
          },
          "required": [
            "$date"
          ]
        },
        "finishedDate": {
          "type": "object",
          "properties": {
            "$date": {
              "type": "string"
            }
          },
          "required": [
            "$date"
          ]
        },
        "modifyDate": {
          "type": "object",
          "properties": {
            "$date": {
              "type": "string"
            }
          },
          "required": [
            "$date"
          ]
        },
        "pointsAwardedDate": {
          "type": "object",
          "properties": {
            "$date": {
              "type": "string"
            }
          },
          "required": [
            "$date"
          ]
        },
        "pointsEarned": {
          "type": "string"
        },
        "purchaseDate": {
          "type": "object",
          "properties": {
            "$date": {
              "type": "string"
            }
          },
          "required": [
            "$date"
          ]
        },
        "purchasedItemCount": {
          "type": "number"
        },
        "rewardsReceiptItemList": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "barcode": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "discountedItemPrice": {
                "type": "string"
              },
              "finalPrice": {
                "type": "string"
              },
              "itemPrice": {
                "type": "string"
              },
              "originalReceiptItemText": {
                "type": "string"
              },
              "partnerItemId": {
                "type": "string"
              },
              "priceAfterCoupon": {
                "type": "string"
              },
              "quantityPurchased": {
                "type": "number"
              },
              "needsFetchReview": {
                "type": "boolean"
              },
              "preventTargetGapPoints": {
                "type": "boolean"
              },
              "userFlaggedBarcode": {
                "type": "string"
              },
              "userFlaggedNewItem": {
                "type": "boolean"
              },
              "userFlaggedPrice": {
                "type": "string"
              },
              "userFlaggedQuantity": {
                "type": "number"
              },
              "competitiveProduct": {
                "type": "boolean"
              },
              "originalMetaBriteBarcode": {
                "type": "string"
              },
              "pointsEarned": {
                "type": "string"
              },
              "pointsPayerId": {
                "type": "string"
              },
              "rewardsGroup": {
                "type": "string"
              },
              "rewardsProductPartnerId": {
                "type": "string"
              },
              "targetPrice": {
                "type": "string"
              },
              "brandCode": {
                "type": "string"
              },
              "competitorRewardsGroup": {
                "type": "string"
              },
              "pointsNotAwardedReason": {
                "type": "string"
              },
              "needsFetchReviewReason": {
                "type": "string"
              },
              "userFlaggedDescription": {
                "type": "string"
              },
              "itemNumber": {
                "type": "string"
              },
              "originalMetaBriteQuantityPurchased": {
                "type": "number"
              },
              "metabriteCampaignId": {
                "type": "string"
              },
              "originalMetaBriteDescription": {
                "type": "string"
              },
              "originalFinalPrice": {
                "type": "string"
              },
              "originalMetaBriteItemPrice": {
                "type": "string"
              },
              "deleted": {
                "type": "boolean"
              }
            },
            "required": [
              "partnerItemId"
            ]
          }
        },
        "rewardsReceiptStatus": {
          "type": "string"
        },
        "totalSpent": {
          "type": "string"
        },
        "userId": {
          "type": "string"
        }
      },
      "required": [
        "_id",
        "createDate",
        "dateScanned",
        "modifyDate",
        "rewardsReceiptStatus",
        "userId"
      ]
    }
  }

=== L3P3titPrince/015_FetchRewards_HW/data/test_2.json
{
    "_id": {
      "$oid": "5ff1e1eb0a720f0523000575"
    },
    "bonusPointsEarned": 500,
    "bonusPointsEarnedReason": "Receipt number 2 completed, bonus point schedule DEFAULT (5cefdcacf3693e0b50e83a36)",
    "createDate": {
      "$date": "2021-01-03T15:25:31.000Z"
    },
    "dateScanned": {
      "$date": "2021-01-03T15:25:31.000Z"
    },
    "finishedDate": {
      "$date": "2021-01-03T15:25:31.000Z"
    },
    "modifyDate": {
      "$date": "2021-01-03T15:25:36.000Z"
    },
    "pointsAwardedDate": {
      "$date": "2021-01-03T15:25:31.000Z"
    },
    "pointsEarned": "500.0",
    "purchaseDate": {
      "$date": "2021-01-03T00:00:00.000Z"
    },
    "purchasedItemCount": 5,
    "rewardsReceiptItemList": [
      {
        "barcode": "4011",
        "description": "ITEM NOT FOUND",
        "finalPrice": "26.00",
        "itemPrice": "26.00",
        "needsFetchReview": false,
        "partnerItemId": "1",
        "preventTargetGapPoints": true,
        "quantityPurchased": 5,
        "userFlaggedBarcode": "4011",
        "userFlaggedNewItem": true,
        "userFlaggedPrice": "26.00",
        "userFlaggedQuantity": 5
      }
    ],
    "rewardsReceiptStatus": "FINISHED",
    "totalSpent": "26.00",
    "userId": "5ff1e1eacfcf6c399c274ae6"
  }
