=== L3P3titPrince/015_FetchRewards_HW/data/users_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Generated schema for Root",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "object",
          "properties": {
            "$oid": {
              "type": "string"
            }
          },
          "required": [
            "$oid"
          ]
        },
        "active": {
          "type": "boolean"
        },
        "createdDate": {
          "type": "object",
          "properties": {
            "$date": {
              "type": "string"
            }
          },
          "required": [
            "$date"
          ]
        },
        "lastLogin": {
          "type": "object",
          "properties": {
            "$date": {
              "type": "string"
            }
          },
          "required": [
            "$date"
          ]
        },
        "role": {
          "type": "string"
        },
        "signUpSource": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      },
      "required": [
        "_id",
        "active",
        "createdDate",
        "role"
      ]
    }
  }

=== L3P3titPrince/015_FetchRewards_HW/data/test_1.users_raw.json
[{
  "_id": {
    "$oid": "5ff1e194b6a9d73a3a9f1052"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-03T15:24:04.800Z"
  },
  "lastLogin": {
    "$date": "2021-01-03T15:25:37.858Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff1e1eacfcf6c399c274ae6"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-03T15:25:30.554Z"
  },
  "lastLogin": {
    "$date": "2021-01-03T15:25:30.597Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff1e1e8cfcf6c399c274ad9"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-03T15:25:28.354Z"
  },
  "lastLogin": {
    "$date": "2021-01-03T15:25:28.392Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff1e1b7cfcf6c399c274a5a"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-03T15:24:39.626Z"
  },
  "lastLogin": {
    "$date": "2021-01-03T15:24:39.665Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff1e1f1cfcf6c399c274b0b"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-03T15:25:37.564Z"
  },
  "lastLogin": {
    "$date": "2021-01-03T15:25:37.599Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff1e1e4cfcf6c399c274ac3"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-03T15:25:24.656Z"
  },
  "lastLogin": {
    "$date": "2021-01-03T15:25:24.694Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff1e1b4cfcf6c399c274a54"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-03T15:24:36.410Z"
  },
  "lastLogin": {
    "$date": "2021-01-03T15:24:36.452Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff370c562fde912123a5e0e"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-04T19:47:17.776Z"
  },
  "lastLogin": {
    "$date": "2021-01-04T19:50:50.563Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff36d0362fde912123a5535"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-04T19:31:15.973Z"
  },
  "lastLogin": {
    "$date": "2021-01-04T19:34:42.944Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff36d83135e7011bcb864d6"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-04T19:33:23.244Z"
  },
  "lastLogin": {
    "$date": "2021-01-04T19:33:23.425Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff36c8862fde912123a538a"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-04T19:29:12.943Z"
  },
  "lastLogin": {
    "$date": "2021-01-04T19:29:13.141Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff36be7135e7011bcb856d3"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-04T19:26:31.239Z"
  },
  "lastLogin": {
    "$date": "2021-01-04T19:29:52.726Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff36a3862fde912123a4460"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-04T19:19:20.352Z"
  },
  "lastLogin": {
    "$date": "2021-01-04T19:23:05.340Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff36c8e135e7011bcb85da4"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-04T19:29:18.994Z"
  },
  "lastLogin": {
    "$date": "2021-01-04T19:29:19.173Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff3711e62fde912123a620e"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-04T19:48:46.807Z"
  },
  "lastLogin": {
    "$date": "2021-01-04T19:48:46.997Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff4ce33c3d63511e2a484b6"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-05T20:38:11.229Z"
  },
  "lastLogin": {
    "$date": "2021-01-05T20:39:55.131Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff473e7c1e2d0121a9b2697"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-05T14:12:55.669Z"
  },
  "lastLogin": {
    "$date": "2021-01-05T14:12:55.877Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff47392c3d63511e2a47881"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-05T14:11:30.233Z"
  },
  "lastLogin": {
    "$date": "2021-01-05T14:15:33.550Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff4ce91c1e2d0121a9b3057"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-05T20:39:45.282Z"
  },
  "lastLogin": {
    "$date": "2021-01-05T20:39:45.329Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff4ce3dc3d63511e2a484dc"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-05T20:38:21.887Z"
  },
  "lastLogin": {
    "$date": "2021-01-05T20:38:21.938Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff4ce34c3d63511e2a484ba"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-05T20:38:12.503Z"
  },
  "lastLogin": {
    "$date": "2021-01-05T20:38:12.565Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff4ce3ac1e2d0121a9b2fb3"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-05T20:38:18.446Z"
  },
  "lastLogin": {
    "$date": "2021-01-05T20:38:18.495Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff5d15aeb7c7d12096d91a2"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-06T15:03:54.680Z"
  },
  "lastLogin": {
    "$date": "2021-01-06T15:08:10.009Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff5d1a38f142f11dd1886ba"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-06T15:05:07.667Z"
  },
  "lastLogin": {
    "$date": "2021-01-06T15:05:07.878Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff5d1d08f142f11dd18884c"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-06T15:05:52.484Z"
  },
  "lastLogin": {
    "$date": "2021-01-06T15:05:52.717Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff7264e8f142f11dd189504"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-07T15:18:38.596Z"
  },
  "lastLogin": {
    "$date": "2021-01-07T15:20:26.821Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff7401ceb7c7d31ca8a46e0"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-07T17:08:44.072Z"
  },
  "lastLogin": {
    "$date": "2021-01-07T17:08:44.352Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff73bea8f142f3276c3e84a"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-07T16:50:50.206Z"
  },
  "lastLogin": {
    "$date": "2021-01-07T16:50:50.255Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff74f3db3348b11c93361d1"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-07T18:13:17.921Z"
  },
  "lastLogin": {
    "$date": "2021-01-07T18:17:03.217Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff73b90eb7c7d31ca8a452b"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-07T16:49:20.959Z"
  },
  "lastLogin": {
    "$date": "2021-01-07T16:51:07.267Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff7930fb3348b11c93372a6"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-07T23:02:39.759Z"
  },
  "lastLogin": {
    "$date": "2021-01-07T23:09:54.656Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff7268eeb7c7d12096da2a9"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-07T15:19:42.584Z"
  },
  "lastLogin": {
    "$date": "2021-01-07T15:19:42.630Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff726a0eb7c7d12096da2db"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-07T15:20:00.299Z"
  },
  "lastLogin": {
    "$date": "2021-01-07T15:20:00.353Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff793dd04929111f6e90c69"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-07T23:06:05.503Z"
  },
  "lastLogin": {
    "$date": "2021-01-07T23:06:05.681Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff7949eb3348b11c93373d2"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-07T23:09:18.699Z"
  },
  "lastLogin": {
    "$date": "2021-01-07T23:09:18.840Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff7268c8f142f11dd189579"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-07T15:19:40.196Z"
  },
  "lastLogin": {
    "$date": "2021-01-07T15:19:40.243Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "WI"
},
{
  "_id": {
    "$oid": "5ff616a68f142f11dd189163"
  },
  "active": true,
  "createdDate": {
    "$date": "2021-01-06T19:59:34.996Z"
  },
  "role": "consumer",
  "signUpSource": "Email",
  "state": "KY"
},
{
  "_id": {
    "$oid": "5ff79464b3348b11c933738b"
  },
  "active": true,
  "createdDate": {
